onlinestore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("store/", include("store.urls")),
    path('admin/', admin.site.urls),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    # ex: /store/
    path("", views.menu, name="menu"),
    # ex: /store/performance/
    path("performance/", views.performance, name="performance"),
    path("search/", views.search, name="search"),
    path("insert/", views.insert, name="insert"),
    path("delete/", views.delete, name="delete"),
    path("sort/", views.sort, name="sort"),
    path('managedata/', views.manage_data, name='managedata')

]

store/models.py
from django.db import models

# Create your models here.

store/views.py
import pandas as pd
from django.shortcuts import render
from .modules.main import *
from .modules.generateddata import *


def load_data_structures():
    """
    Initialize the BTreeIndex and HashMapIndex with data loaded from a CSV file.

    Returns:
    - b_tree_index: B-tree index loaded with data.
    - hash_map_index: Hash map index loaded with data.
    """
    data = load_data_from_csv()
    if data is not None:
        b_tree_index = BTreeIndex()
        hash_map_index = HashMapIndex()
        for _, row in data.iterrows():
            product_id = row['ProductID']
            price = row['Price']
            b_tree_index.insert(product_id, price)
            hash_map_index.insert(product_id, price)

        return b_tree_index, hash_map_index
    return None, None


def generate_random_data():
    """
    Generates a DataFrame with random ProductIDs and Prices.
    """
    product_ids = random.sample(range(1000000, 2000000), 120000)
    prices = np.random.randint(10, 1000, size=120000)
    itemdata = pd.DataFrame({'ProductID': product_ids, 'Price': prices})
    return itemdata


def manage_data(request):
    productdata = load_data_from_csv()
    if productdata is not None:
        if not productdata.empty:
            context = {"message": f"Data already Generated."}
            return render(request, 'managedata.html', context)
    productdata = generate_random_data()
    save_data_to_csv(productdata)
    context = {"message": f"Data Generated."}
    return render(request, 'managedata.html', context)


def menu(request):
    return render(request, 'menu.html')


def search(request):
    b_tree_index, hash_map_index = load_data_structures()
    if b_tree_index is None or hash_map_index is None:
        return render(request, 'nodata.html')
    if request.method == "POST":
        product_id = int(request.POST.get("product_id"))

        start_time = time.time()
        b_price = b_tree_index.search(product_id)
        end_time = time.time()
        b_time = end_time - start_time

        start_time = time.time()
        h_price = hash_map_index.search(product_id)
        end_time = time.time()
        h_time = end_time - start_time

        context = {
            "product_id": product_id,
            "b_price": b_price,
            "h_price": h_price,
            "b_time": b_time,
            "h_time": h_time,
        }

        return render(request, "search.html", context)
    return render(request, "search.html")


def insert(request):
    b_tree_index, hash_map_index = load_data_structures()
    if b_tree_index is None or hash_map_index is None:
        return render(request, 'nodata.html')
    if request.method == "POST":
        product_id = int(request.POST.get("product_id"))
        price = int(request.POST.get("price"))

        start_time = time.time()
        b_tree_index.insert(product_id, price)
        end_time = time.time()
        b_time = end_time - start_time

        start_time = time.time()
        hash_map_index.insert(product_id, price)
        end_time = time.time()
        h_time = end_time - start_time

        data = load_data_from_csv()
        data.loc[len(data)] = [product_id, price]
        save_data_to_csv(data)

        context = {
            "product_id": product_id,
            "price": price,
            "b_time": b_time,
            "h_time": h_time,
        }

        return render(request, "insert.html", context)
    return render(request, "insert.html")


def delete(request):
    b_tree_index, hash_map_index = load_data_structures()
    if b_tree_index is None or hash_map_index is None:
        return render(request, 'nodata.html')
    if request.method == "POST":
        product_id = int(request.POST.get("product_id"))

        start_time = time.time()
        b_tree_index.delete(product_id)
        end_time = time.time()
        b_time = end_time - start_time

        start_time = time.time()
        hash_map_index.delete(product_id)
        end_time = time.time()
        h_time = end_time - start_time

        data = load_data_from_csv()
        updatedata = data[data['ProductID'] != product_id]
        save_data_to_csv(updatedata)

        context = {
            "product_id": product_id,
            "b_time": b_time,
            "h_time": h_time,
        }

        return render(request, "delete.html", context)
    return render(request, "delete.html")


def sort(request):
    b_tree_index, hash_map_index = load_data_structures()
    if b_tree_index is None or hash_map_index is None:
        return render(request, 'nodata.html')

    b_time, b_sorted = test_sort(b_tree_index)
    h_time, h_sorted = test_sort(hash_map_index)

    sorteddata = pd.DataFrame(b_sorted, columns=['ProductID', 'Price'])
    save_data_to_csv(sorteddata)
    context = {
        "b_sorted": b_sorted[:100],
        "h_sorted": h_sorted,
        "b_time": b_time,
        "h_time": h_time,
    }

    return render(request, "sort.html", context)


def performance(request):
    b_tree_index, hash_map_index = load_data_structures()
    if b_tree_index is None or hash_map_index is None:
        return render(request, 'nodata.html')

    data = load_data_from_csv()
    search_keys = random.sample(data['ProductID'].tolist(), 1000)
    delete_keys = random.sample(data['ProductID'].tolist(), 1000)
    new_product_ids = random.sample(range(1000000, 2000000), 1000)
    new_prices = np.random.randint(10, 1000, size=1000)
    insert_items = list(zip(new_product_ids, new_prices))

    b_search_time = test_search(b_tree_index, search_keys)
    b_insert_time = test_insert(b_tree_index, insert_items)
    b_delete_time = test_delete(b_tree_index, delete_keys)
    b_sort_time, _ = test_sort(b_tree_index)

    h_search_time = test_search(hash_map_index, search_keys)
    h_insert_time = test_insert(hash_map_index, insert_items)
    h_delete_time = test_delete(hash_map_index, delete_keys)
    h_sort_time, _ = test_sort(hash_map_index)

    results = pd.DataFrame({
        'Operation': ['Search', 'Insert', 'Delete', 'Sort'],
        'B-Tree Time (s)': [b_search_time, b_insert_time, b_delete_time, b_sort_time],
        'Hash Map Time (s)': [h_search_time, h_insert_time, h_delete_time, h_sort_time]
    })
    results['Speedup (%)'] = ((results['B-Tree Time (s)'] - results['Hash Map Time (s)']) / results[
        'B-Tree Time (s)']) * 100

    results['Speedup (%)'] = results['Speedup (%)'].round(2)
    barchart = plot_speedup_bar_chart(results)
    groupbarchart = plot_grouped_bar_chart(results)
    linechart = plot_line_chart(results)
    piechart = plot_pie_charts(results)
    context = {
        'barchart': barchart,
        'groupbarchart': groupbarchart,
        'linechart': linechart,
        'piechart': piechart,
    }
    return render(request, 'performance.html', context)

store/templates/delete.html
<html>
<head>
    <title>Delete Products</title>
</head>
<style>
          h1 {
              text-align: center;
              background: rgba(76, 175, 80, 0.3);
          }
          p {
              display: inline-block;
              border:2px solid dodgerblue;
              height: 50px; /*sets height of element*/
              background: cornflowerblue; /*sets the background of this element (here a solid colour)*/
              transition: all 0.6s; /*sets a transition (for hover effect)*/
              padding-left: 20px; /*sets 'padding'*/
              padding-right: 20px; /*sets 'padding'*/
              line-height: 50px; /*for this, it sets vertical alignment*/
          }
          p:hover {
              background: tomato; /*sets background colour*/
          }
          html, body {
              height: 100%;
              margin: 0;
              padding: 0;
              width: 100%;
          }

          body {
              display: table;
              background-color: lavender;
          }
          .container {
              text-align: center;
              display: table-cell;
              vertical-align: middle;
          }
          .footer{
              background-color: rgba(100, 149, 237, 0.9);
              width: 100%;
              position: fixed;
              text-align: center;
              bottom: 0px;
          }
    </style>
<body>
 <div class="container">
     <h1>Delete Product</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="product_id" class="prompt" style="bottom: 60%;" >Enter ProductID to delete:</label><br>
        <input type="number" class="prompt" style="bottom: 50%;" id="product_id" name="product_id" required><br><br>
        <input type="submit" class="b" style="bottom: 40%; right: 39.1%;" value="Delete">
    </form>
    {% if product_id %}
    <p>Deleted ProductID {{ product_id }}.</p>
    <p>B-Tree: Deleted in {{ b_time }} seconds.</p>
    <p>Hash Map: Deleted in {{ h_time }} seconds.</p>
    {% endif %}
    <div class="footer"><a href="../" style="color: blue; text-decoration: none" >Back to Menu</a></div>
 </div>
</body>
</html>

store/templates/insert.html
<html>
<head>
    <title>Insert Products</title>
</head>
<style>
          h1 {
              text-align: center;
              background: rgba(76, 175, 80, 0.3);
          }
          p {
              display: inline-block;
              border:2px solid dodgerblue;
              height: 50px; /*sets height of element*/
              background: cornflowerblue; /*sets the background of this element (here a solid colour)*/
              transition: all 0.6s; /*sets a transition (for hover effect)*/
              padding-left: 20px; /*sets 'padding'*/
              padding-right: 20px; /*sets 'padding'*/
              line-height: 50px; /*for this, it sets vertical alignment*/
          }
          p:hover {
              background: tomato; /*sets background colour*/
          }
          html, body {
              height: 100%;
              margin: 0;
              padding: 0;
              width: 100%;
          }

          body {
              display: table;
              background-color: lavender;
          }
          .container {
              text-align: center;
              display: table-cell;
              vertical-align: middle;
          }
          .footer{
              background-color: rgba(100, 149, 237, 0.9);
              width: 100%;
              position: fixed;
              text-align: center;
              bottom: 0px;
          }
    </style>
<body>
<div class="container">
    <h1>Insert Product</h1>
<form method="POST">
    {% csrf_token %}
    <label for="product_id" class="prompt" style="bottom: 60%;" >Enter new ProductID to insert:</label><br>
    <input type="number" class="prompt" style ="bottom: 50%; left: 43.6%;" id="product_id" name="product_id" required><br><br>
    <label for="price" class="prompt" style="bottom: 40%; left: 47.6%;" >Enter Price:</label><br>
    <input type="text" class="prompt" style ="bottom: 30%; left: 43.6%;" id="price" name="price" required><br><br>
    <input type="submit" class="container" style="bottom: 20%; right: 39.1%;" value="Insert">
</form>
{% if product_id %}
    <p>Inserted ProductID {{ product_id }} with a price of ${{ price }}.</p>
    <p>B-Tree: Inserted in {{ b_time }} seconds.</p>
    <p>Hash Map: Inserted in {{ h_time }} seconds.</p>
{% endif %}
<div class="footer"><a href="../" style="color: blue; text-decoration: none" >Back to Menu</a></div>
</body>
</html>

store/templates/menu.html
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>Online Store Database</title>
      <style>
          h1 {
              background: rgba(76, 175, 80, 0.3)
          }
          a {
              display: inline-block;
              border:2px solid dodgerblue;
              height: 50px; /*sets height of element*/
              background: cornflowerblue; /*sets the background of this element (here a solid colour)*/
              transition: all 0.6s; /*sets a transition (for hover effect)*/
              padding-left: 20px; /*sets 'padding'*/
              padding-right: 20px; /*sets 'padding'*/
              line-height: 50px; /*for this, it sets vertical alignment*/
          }
          a:hover {
              background: tomato; /*sets background colour*/
          }
          html, body {
              height: 100%;
              margin: 0;
              padding: 0;
              width: 100%;
          }

          body {
              display: table;
              background-color: lavender;
          }
          .container {
              text-align: center;
              display: table-cell;
              vertical-align: middle;
          }
    </style>
  </head>
  <body>
  <div class="container">
    <h1>=== Online Store Database Index System ===</h1>
    <a href="{%url 'store:search' %}" style="color: black; text-decoration: none" >== Search Product ==</a><br><br>
    <a href="{%url 'store:insert' %}" style="color: black; text-decoration: none" >== Insert Product ==</a><br><br>
    <a href="{%url 'store:delete' %}" style="color: black; text-decoration: none" >== Delete Product ==</a><br><br>
    <a href="{%url 'store:sort' %}" style="color: black; text-decoration: none" >== Sort Products ==</a><br><br>
    <a href="{%url 'store:performance' %}" style="color: black; text-decoration: none" >== Compare Performance ==</a><br><br>
    <a href="{%url 'store:managedata' %}" style="color: black; text-decoration: none" >== Generate Data ==</a><br><br>

  </div>
  </body>
</html>

store/templates/performance.html
<!doctype html>
{% load custom_filters %}
<html>
<head>
    <title>Performance Results</title>
</head>
<style>
          h1 {
              text-align: center;
              background: rgba(76, 175, 80, 0.3);
          }

          html, body {
              height: 100%;
              margin: 0;
              padding: 0;
              width: 100%;
          }

          body {
              display: table;
              background-color: lavender;
          }
          .container {
              text-align: center;
              display: table-cell;
              vertical-align: middle;
          }
          .footer{
              background-color: rgba(100, 149, 237, 0.9);
              width: 100%;
              position: fixed;
              text-align: center;
              bottom: 0px;
          }
          .container {
              align-items: center;
              float: left;
          }
          .image{
              float: left;
              padding: 29px;
          }
    </style>
<body>
    <h1>Performance Plots</h1>
    <div class="imageholder">
        <div class="image"><img src="data:image/png;base64,{{ barchart|base64encode }}" width="700" height="420"></div>
        <div class="image"><img src="data:image/png;base64,{{ groupbarchart|base64encode }}" width="700" height="420"></div>
        <div class="image"><img src="data:image/png;base64,{{ linechart|base64encode }}" width="700" height="420"></div>
        <div class="image"><img src="data:image/png;base64,{{ piechart|base64encode }}" width="700" height="420"></div>
    </div>
    <div class="footer"><a href="../" style="color: blue; text-decoration: none" >Back to Menu</a></div>
</body>
</html>

store/templates/search.html
<html>
<head>
    <title>Search Products</title>
</head>
<style>
          h1 {
              text-align: center;
              background: rgba(76, 175, 80, 0.3);
          }
          p {
              display: inline-block;
              border:2px solid dodgerblue;
              height: 50px; /*sets height of element*/
              background: cornflowerblue; /*sets the background of this element (here a solid colour)*/
              transition: all 0.6s; /*sets a transition (for hover effect)*/
              padding-left: 20px; /*sets 'padding'*/
              padding-right: 20px; /*sets 'padding'*/
              line-height: 50px; /*for this, it sets vertical alignment*/
          }
          p:hover {
              background: tomato; /*sets background colour*/
          }
          html, body {
              height: 100%;
              margin: 0;
              padding: 0;
              width: 100%;
          }

          body {
              display: table;
              background-color: lavender;
          }
          .container {
              text-align: center;
              display: table-cell;
              vertical-align: middle;
          }
          .footer{
              background-color: rgba(100, 149, 237, 0.9);
              width: 100%;
              position: fixed;
              text-align: center;
              bottom: 0px;
          }
    </style>
<body>
 <div class="container">
<h1>Search Product</h1>
<form method="POST">
    {% csrf_token %}
    <label for="product_id" class="prompt"  style="bottom: 59%; left: 43.5%;" >Enter ProductID to search:</label><br>
    <input type="number" class="prompt" style ="bottom: 50%; left: 43.6%;" id="product_id" name="product_id" required><br><br>
    <input type="submit" class="container" style="bottom: 40%; right: 39%;" value="Search">
</form>
{% if product_id %}
    <p>ProductID {{ product_id }} has a price of ${{ b_price }}.</p>
    <p>B-Tree: Found in {{ b_time }} seconds.</p>
    <p>Hash Map: Found in {{ h_time }} seconds.</p>
{% endif %}
<div class="footer"><a href="../" style="color: blue; text-decoration: none" >Back to Menu</a></div>
 </div>
</body>
</html>